use crate::model::aspected_items::AspectedItems;
use crate::model::aspects::Aspects;
use crate::model::consider_books::ConsiderBooks;
use crate::model::lessons::Lessons;
use crate::model::recipe::Recipes;
use crate::model::save::Autosave;
use crate::model::skills::Skills;
use crate::model::tomes::Tomes;

pub(crate) static RECIPE_FILES: &[&str] = &[
    "__debug.json",
    "_backstops.json",
    "_collections.json",
    "_intercepts.json",
    "_legacy_crafting_4a_prenticeplus_ambittable_unfriendly.json",
    "_legacy_crafting_obsolete.json",
    "_legacy.json",
    "_startup_recipes.json",
    "0_consider_decontaminations.json",
    "1_consider_books.json",
    "2a_consider_open.json",
    "2b_consider_generic.json",
    "2c_consider_resolve.json",
    "beasts.json",
    "bookbinding.json",
    "celestial_recipes_time.json",
    "celestial_recipes_weather.json",
    "correspondence_ordering.json",
    "correspondence.json",
    "crafting_0_numina.json",
    "crafting_0_rest.json",
    "crafting_1_chandlery.json",
    "crafting_1_evolutions.json",
    "crafting_1_simplemanipulations.json",
    "crafting_2_keeper.json",
    "crafting_3_scholar.json",
    "crafting_4b_prentice.json",
    "DLC_HOL_1_lighthouse.json",
    "DLC_HOL_1_meddling.json",
    "DLC_HOL_1a_salons_inauguration_end.json",
    "DLC_HOL_1b_salons_inauguration_ally_foe.json",
    "DLC_HOL_1b_salons_inauguration_mission.json",
    "DLC_HOL_2a_salons_blockers_basic.json",
    "DLC_HOL_2b_salons_blockers_beverages.json",
    "DLC_HOL_2c_salons_blockers_repasts.json",
    "DLC_HOL_3_salons_prototypes.json",
    "DLC_HOL_3b_salons_routing.json",
    "DLC_HOL_cooking.json",
    "DLC_HOL_correspondence_summoning.json",
    "DLC_HOL_gathering_2_seasonal.json",
    "DLC_HOL_interactions_specific.json",
    "DLC_HOL_leiter.json",
    "DLC_HOL_manuscripting_soph_improve.json",
    "DLC_HOL_manuscripting_soph_set.json",
    "DLC_HOL_manuscripting_write.json",
    "DLC_HOL_nrs.json",
    "DLC_HOL_patch_resurrect_incidents.json",
    "DLC_HOL_prototype_recipes.json",
    "DLC_HOL_salon_responses.json",
    "DLC_HOL_slnbk_languages.json",
    "DLC_HOL_slnbk_skillls.json",
    "DLC_HOL_slnbk_skills.json",
    "DLC_HOL_understanding_specific.json",
    "DLC_HOL_village_invitations.json",
    "gathering_1_exceptional.json",
    "gathering_2_seasonal.json",
    "other_activities.json",
    "renounce.json",
    "talk_1_visitors.json",
    "talk_2_visitors_payments_tutoring.json",
    "talk_3a_visitors_intercepts.json",
    "talk_3b_visitors_cantread.json",
    "talk_4a_visitors_intros.json",
    "talk_4b_visitors_specific_incidents.json",
    "talk_5_visitors_generic_consultations.json",
    "talk_5z_visitors_fallthrough_hints.json",
    "talk_6_assistance.json",
    "terrain.json",
    "understanding_1_numa.json",
    "understanding_2_upskill.json",
    "village_interactions.json",
    "visitors_correspondence_auctions.json",
    "wisdom_commitments_exotic.json",
    "wisdom_commitments.json",
    "z_fallthrough_hints.json",
    "z_fallthrough_placeholders.json",
];

#[derive(Clone)]
pub(crate) struct GameDocuments {
    pub(crate) aspects: Aspects,
    pub(crate) aspected_items: AspectedItems,
    pub(crate) tomes: Tomes,
    pub(crate) consider_books: ConsiderBooks,
    pub(crate) skills: Skills,
    pub(crate) lessons: Lessons,
    //contamination_aspects: dyn GameCollection<QueryType::ContaminationAspects>,
    pub(crate) recipes: Recipes,
    pub(crate) autosave: Autosave,
}